### ISSUE TITLE
https certificate issue on agilemanifesto.org

### ISSUE THREAD

**Issue by Erikmitk** [agilemanifesto/agilemanifesto.github.io#5]
Https works for the github.io domain `https://agilemanifesto.github.io` but it redirects to `http://agilemanifesto.org`.

Trying to open this domain with https://agilemanifesto.org throws a security error because the certificate is configured for *.github.com and the domains obviously do not match.

Since Chrome starts flagging http-sites as not secure I thought I’d raise this issue. Though I don’t think it has high priority.

**Comment by Erikmitk** [comment]
That seems to be fixed so I close this issue. 👍

**Comment by WardCunningham** [comment]
Yes. Finally fixed. Many small complications along the way. I lost track of this issue in the process or I would have closed it myself. Thanks for the follow up.
